apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/argo-cd.yaml
- base/argo-events.yaml
- base/argo-rollouts.yaml
- base/argo-workflows.yaml
- base/argocd-image-updater.yaml
