apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.1.3
    #path: overlays/extensions
    helm:
      releaseName: argo
      values: |
        server:
          extensions:
            enabled: true
            extensionList:
              - name: rollout-extension
                env:
                  - name: EXTENSION_URL
                    value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.4/extension.tar
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true

