apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr
  namespace: argocd
spec:
  project: default
  destination:
    namespace: dapr-system
    server: https://kubernetes.default.svc
  source:
    chart: dapr
    repoURL: https://dapr.github.io/helm-charts
    targetRevision: 1.14.0
    helm:
      releaseName: dapr
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true

